CREATE TABLE FoodDataTable(
   ID                  INTEGER  NOT NULL IDENTITY (1,1) PRIMARY KEY 
  ,vegetable           VARCHAR(20) NOT NULL
  ,"Serving size"      VARCHAR(33) NOT NULL
  ,"Country of origin" VARCHAR(116) NOT NULL
  ,Storage             VARCHAR(170) NOT NULL
  ,Packaging           VARCHAR(68)
  ,Stock               INTEGER  NOT NULL
  ,Category            VARCHAR(19) NOT NULL
  ,Price               VARCHAR(5)
);
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Artichoke','This pack contains 4 servings','Packed in United Kingdom','For use by date: see front of pack. Keep refrigerated, once opened consume within 3 days and do not exceed the use by date. Not suitable for home freezing','Recycle pot. Don''t Recycle film',24,'chilled','£3.00');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Red onion','This pack contains servings','Grown in Egypt, Netherlands, New Zealand, Spain, United Kingdom','At home, store in a cool, dry place.',NULL,4,'vegetables','£0.95');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Spinach','This pack contains 1 servings','Packed in United Kingdom','For use by date: see front of pack. Keep refrigerated, once opened consume within 48 hours and do not exceed the use by date.','Recycle with bags at large supermarket, Don''t recycle at home film',60,'salad','£1.20');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Sweet potato','This pack contains n/a servings','Grown in Egypt, Guatemala, Honduras, Portugal, South Africa, Spain, United States','For best before date: see front of pack. Store in a cool, dry place.',NULL,19,'vegetables','£1.09');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Baking potato','This pack contains 4 servings','Grown in United Kingdom','At home, refrigerate for freshness. Wash before use. For best before date: see front of pack.','Film - Recycle with bags at large supermarket. Don''t recycle at home',20,'vegetables','£0.70');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Maris piper potato','This pack contains 14 servings','Grown in United Kingdom','At home, refrigerate for freshness. Wash before use. For best before date: see front of pack.','Film - Recycle with bags at large supermarket. Don''t recycle at home',44,'vegetables','£1.40');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Asparagus','This pack contains servings','Grown in Italy, Mexico, Peru, Spain','At home, refrigerate for freshness. Wash before use.','Film -Not Yet Recycled',97,'vegetables','£1.99');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Carrot','This pack contains servings','Grown in United Kingdom','For best before date: see front of pack. Keep refrigerated. At home, refrigerate for freshness, wash before use.','Film -Recycle with bags at large supermarket. Don''t recycle at home',4,'vegetables','£0.65');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Cauliflower','This pack contains servings','Grown in France, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness, wash before use.',NULL,89,'vegetables','£0.99');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Celery','This pack contains servings','Grown in Spain, United Kingdom','For best before date: see front of pack. Keep refrigerated. At home, refrigerate for freshness. Wash before use.',NULL,58,'salad','£0.57');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Yellow pepper','This pack contains 100g servings','Grown in Israel, Morocco, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,91,'salad','£0.55');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Green pepper','This pack contains 100g servings','Grown in Israel, Morocco, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,91,'salad','£0.55');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Red cabbage','This pack contains servings','Grown in United Kingdom','At home, refrigerate for freshness. Wash before use.','Label - Don''t Recycle',81,'salad',NULL);
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Leek','This pack contains servings','Grown in Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.','Film - Don''t Recycle',85,'vegetables','£1.19');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Lettuce','This pack contains servings','Grown in Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,4,'salad','£0.75');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Mushroom','This pack contains servings','Grown in Ireland, United Kingdom','At home, refrigerate for freshness. Wash before use.','Punnet-Recycle. Film - Recycle at larger stores',55,'vegetables','£0.89');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Parsnip','This pack contains servings','Grown in United Kingdom','At home, refrigerate for freshness. Wash before use.','Film. Recycle with bags at large supermarket. Don''t recycle at home',93,'vegetables','£0.65');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Beetroot','This pack contains 1 servings','Packed in United Kingdom','Once opened, keep refrigerated and use within 3 days.','Don''t recycle film',14,'salad','£0.40');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Pepper','This pack contains 100g servings','Grown in Israel, Morocco, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,51,'salad','£0.55');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Mini potato','This pack contains 4 servings','Grown in Belgium, Cyprus, Egypt, France, Ireland, Israel, Jersey, Spain, United Kingdom','For best before date: see front of pack. At home, refrigerate for freshness. Wash before use.','Film- Recycle with bags at large supermarket. Don''t recycle at home',48,'vegetables','£1.20');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Radish','This pack contains servings','Packed in United Kingdom','At home, refrigerate for freshness. Wash before use. For best before date: see front of pack. Keep refrigerated.','Film- Recycle with bags at large supermarket. Don''t recycle at home',54,'salad','£0.49');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Red pepper','This pack contains 100g servings','Grown in Israel, Morocco, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,91,'salad','£0.55');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Broccoli','This pack contains servings','Grown in Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,43,'vegetables','£2.19');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Brussels sprouts','This pack contains servings','Grown in Netherlands, United Kingdom','At home, refrigerate for freshness, wash before use. See reverse for cooking instructions.','Film - Not Yet Recycled',72,'vegetables','£1.00');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Cabbage','This pack contains servings','Grown in Spain, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,67,'salad','£0.67');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Whole Cucumber','This pack contains 100 g servings','Grown in Greece, Morocco, Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use. For best flavour, serve at room temperature.','Film packaging - Not yet recycled.',54,'salad','£0.89');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Aubergine','This pack contains - servings','Grown in Netherlands, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use. For best flavour, serve at room temperature.','PLU label -Not yet recycled',91,'vegetables','£0.89');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Garlic','This pack contains servings','Grown in Spain','At home, store in a cool, dry place.',NULL,48,'herbs & ingredients','£0.24');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Green beans','This pack contains servings','Grown in Egypt, Guatemala, Kenya','For best before date: see front of pack. At home, refrigerate for freshness. Wash before use.','Film -Recycle with bags at large supermarket. Don''t recycle at home',30,'vegetables','£1.25');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Red chilies','This pack contains 1 servings','Grown in Bulgaria, Egypt, France, Gambia, India, Jersey, Kenya, Morocco, Netherlands, Senegal, Spain, United Kingdom','At home, refrigerate for freshness. Wash before use. Leftover chillies can be frozen whole or sliced for up to one month. Easy to chop from frozen.','Pre-printed film. Not Yet Recycled',73,'chilled','£0.57');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Butternut squash','This pack contains servings','Grown in Argentina, Brazil, Egypt, Greece, Morocco, Portugal, Senegal, South Africa, Spain','At home, store in a cool, dry place. Wash before use.',NULL,15,'vegetables','£1.50');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Courgette','This pack contains servings','Grown in Morocco, Spain, United Kingdom','At home, store in a cool, dry place. Wash before use.',NULL,51,'vegetables','£2.78');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Spring Onion','This pack contains servings','Grown in Egypt, Germany, Italy, Mexico, Morocco, Senegal, United Kingdom','At home, refrigerate for freshness. Wash before use.',NULL,15,'salad','£0.55');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Avocado','This pack contains 1 servings','Grown in Brazil, Chile, Colombia, Israel, Kenya, Mexico, Morocco, Peru, South Africa, Spain, Tanzania','At home, refrigerate for freshness. Wash before use. For best flavour, serve at room temperature.','PLU Label-- Don''t Recycle',27,'salad','£0.75');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Classic Tomatoes','This pack contains n/a servings','Grown in United Kingdom','At home, refrigerate for freshness. Wash before use. For best flavour, serve at room temperature.','Film - Do Not Recycle',60,'salad','£0.90');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Cherry Vine Tomatoes','This pack contains servings','Grown in United Kingdom','At home, store in a cool, dry place away from direct sunlight and serve at room temperature to maximise flavour. Wash before use. For best before date: see front of pack.','Film -Not yet recycled. Punnet -Widely recycled',61,'salad','£2.25');
INSERT INTO FoodDataTable(vegetable,"Serving size","Country of origin",Storage,Packaging,Stock,Category,Price) VALUES ('Wild Rocket','This pack contains 1 servings','Packed in United Kingdom','For use by date: see front of pack. Keep refrigerated, once opened consume within 48 hours and do not exceed the use by date.','Recycle with bags at large supermarket, Don''t recycle at home film',93,'salad','£1.00');